steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/dash-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/dash-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'dash-app',
         '--image', 'gcr.io/$PROJECT_ID/dash-app',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated']
images:
- 'gcr.io/$PROJECT_ID/dash-app'